name: CI - Build & Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mrazota-backend:latest

      - name: Build and push mrazota-site image
        uses: docker/build-push-action@v4
        with:
          context: ./mrazota-site
          file: ./mrazota-site/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mrazota-site:latest

      - name: Notify
        run: echo "Images built and pushed. Configure your host to pull these images."
